import { Rubik,Playfair_Display } from '@next/font/google';
import Head from 'next/head'
import '@/styles/globals.css'

import Header from '@/components/Header';
import Footer from '@/components/Footer';

const rubik = Rubik({
  variable: "--rubik-font",
  weight: ['400','500'],
  subsets: ['latin'],
});
const playfair = Playfair_Display({
  variable: "--playfair-font",
  weight: ['400','500'],
  subsets: ['latin'],
});


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Kaufmann Bau</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${rubik.variable} ${playfair.variable} font-sans bg-primary-black text-white font-normal text-sm leading-[22px]`}>
        <Header/>
        <Component {...pageProps} />
        <Footer />
      </main>
    </>
  )
}
